require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CyberBullyingReactNativeCLI' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-tesseract-ocr', :path => '../node_modules/react-native-tesseract-ocr'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-image-base64', :path => '../node_modules/react-native-image-base64'


  pod 'react-native-background-actions', :path => '../node_modules/react-native-background-actions'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'CyberBullyingReactNativeCLITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CyberBullyingReactNativeCLI-tvOS' do
  # Pods for CyberBullyingReactNativeCLI-tvOS

  target 'CyberBullyingReactNativeCLI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
