export const SET_LOGIN_TRUE = 'SET_LOGIN_TRUE';
export const UPLOAD_MY_POST = 'UPLOAD_MY_POST';
export const SET_LOGN_TRUE_PARENT = 'SET_LOGIN_TRUE_PARENT';
export const REGISTER_SUCCESS_PARENT = 'REGISTER_SUCCESS_PARENT';
export const LOGIN_SUCCESS_PARENT = 'LOGIN_SUCCESS_PARENT';
export const LOGIN_SUCCESS_CHILD = 'LOGIN_SUCCESS_CHILD';
export const REGISTER_SUCCESS_CHILD = 'REGISTER_SUCCESS_CHILD';
